### ISSUE TITLE
Add support for releases

### ISSUE THREAD

**Issue by mboudreau** [odecee/generator-confit#24]
At PageUp, we're using S3 static website hosting with CloudFront (a CDN).  For us to reliably deploy the latest version and great caching on edge servers, we need to invalidate the CloudFront cache when a new version is deployed.  It's a fairly simple process of generating a .cloudfront-invalidate file that holds an array of all paths (files) to be invalidated which is packaged with the add before we do an npm publish to our private npm repository.  Our deployment process does the rest to invalidate cloudfront on those file paths specified.

Because of the opinionated nature of this project, I don't think this might be possible unless there's a way to add extensibility to the generator and make it a bit more general.

**Comment by uglow** [comment]
@mboudreau I've created #25 to discuss extensibility so that this issue can be about releasing.

Some tasks that developers may perform when releasing:
- Ensure all the tests pass (existing `unit test` (& `browser test`?) tasks)
- Ensure code is linted (existing `verify` task)
- Create a production build (existing `build` task)
- Ensure there are no outstanding commits
- Bump the version (there's a few ways this could happen, such as semantic-releasing, using Grunt tasks)
- Create a package
- Publish (deploy?) the package somewhere

In the current Webpack build profile that Confit has, it generates a `webpack.prod.config.js` file which can be safely edited. You could generate the .cloudfront-invalidate file from this point. So it would occur everytime `npm run build` is run.

As for deployment/publishing, there are many ways to do this. What if the (currently unwritten) `release` sub generator asked the following questions:

- How would you like to publish your project?
  - [ ] Semantic Release  *(this is only shown if the project is "public" and the URL of the repo is a GitHub url)*
  - [ ] Publish to private repo
  - [ ] Publish to Artifactory *(for enterprise users)*
  - [ ] Use a custom script

**Comment by mboudreau** [comment]
@uglow just a 'test' tasks, which could encompass unit and e2e.  Linting for sure, but just call it 'lint', not verify, since nobody will know what it's suppose to do.  To create a production build, I normally call that 'release' since my dev build might have a few things different.  You shouldn't worry about git, I think it's outside the scope of Confit.  Version bumping yes, but only when specified, probably it's own task; reason for this is because only our build server can deploy, and as such, can version bump.  I don't think you have to worry about deployment, might be out of scope for now.

I think you might be trying to do too much with confit if you're trying to do the publishing for them and adds a lot of complexity to your project.  I just want a way to be able to create a release of my build and add a task outside of confit.

**Comment by uglow** [comment]
NPM's `package.json` provides built-in support for pre-and-post-task tasks. See [NPM scripts docs](https://docs.npmjs.com/misc/scripts).

Pre-build and post-build tasks look like this in `package.json`:
```console
"scripts": {
    "prebuild": "echo ------------> PRE",
    "build": "npm-run-all clean:prod build:prod",
    "postbuild": "echo ------------> POST",
}
```

I think that will need your immediate...
> I just want a way to be able to create a release of my build and add a task outside of confit.

... needs.
